"""Agentic self-heal: propose fixes for lint issues with confidence weighting.

This is the top-level user-facing feature for the v2 linter. Given a
`.DATA` deck (text or path), the self-heal module:

1. Parses and validates the deck with the v2 linter.
2. For each lint issue, runs the corresponding fix proposal (or asks
   an LLM if no mechanical proposal is registered).
3. Verifies each proposed patched deck against the OPM Flow oracle.
4. Ranks proposals by confidence (a blend of historical calibration
   rate, oracle verdict on the patched deck, and rule severity).
5. Returns a ranked list of FixProposal objects the user can choose
   to apply.

Design philosophy
-----------------

Self-heal is **conservative**: it never auto-applies. The user (or a
downstream agent) reviews each proposal. Self-heal is a sorter, not
an executor.

Calibration-based confidence: the rule-specific historical success
rate from calibration_report.json is the dominant signal. A proposal
for a rule that historically fails 50% of the time is downweighted
regardless of how good it looks in isolation.

Oracle-verified proposals are flagged "verified". A proposal that
keeps the deck passing Flow is verified=True. A proposal that
breaks the deck is verified=False and gets a heavy downweight.

LLM proposals: for issues that don't have a mechanical proposal
function (no rule in `fix_proposals.propose_fix` registry), the
self-heal module can ask an LLM. The LLM is constrained to return a
patched deck that the linter re-parses successfully; this gives us a
free syntax check. LLM proposals are flagged `llm_proposed=True` and
carry the same oracle verification flow.

API
---

```python
from opm_ai.linter.v2.self_heal import SelfHealResult, self_heal_deck

result = self_heal_deck(
    text=deck_text,
    source_file=Path("/path/to/x.DATA"),
    calibration_report=report_dict,  # or None to skip calibration weighting
    use_llm=True,  # ask LLM for issues without mechanical proposals
    oracle_cfg=OracleConfig(),
)
for proposal in result.proposals:
    print(proposal.rule_code, proposal.confidence, proposal.verified, proposal.description)
```
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .calibration import AttemptResult, CalibrationReport, FixtureResult
from .fix_proposals import FixProposal, propose_fix
from .oracle import DEFAULT_TIMEOUT_S, FlowVerdict, OracleConfig, run_flow
from .parser import parse_file
from .resolver import resolve_deck
from .validator import LintIssue, validate


# ---------------------------------------------------------------------------
# Confidence model
# ---------------------------------------------------------------------------

@dataclass
class ScoredProposal:
    """A FixProposal enriched with confidence and verification metadata.

    Attributes:
        proposal: The underlying FixProposal.
        rule_code: The lint rule code.
        confidence: A float in [0, 1]. Higher = more likely to fix the
            issue without breaking anything.
        verified: True iff oracle confirmed the patched deck still
            passes Flow (or started passing).
        llm_proposed: True iff generated by an LLM (not mechanical).
        oracle_verdict: The FlowVerdict on the patched deck.
        rationale: Human-readable explanation of the confidence score.
    """

    proposal: FixProposal
    rule_code: int
    confidence: float
    verified: bool
    llm_proposed: bool
    oracle_verdict: Optional[FlowVerdict] = None
    rationale: str = ""

    def to_dict(self) -> dict:
        return {
            "rule_code": self.rule_code,
            "confidence": round(self.confidence, 3),
            "verified": self.verified,
            "llm_proposed": self.llm_proposed,
            "description": self.proposal.description,
            "original_value": self.proposal.original_value,
            "new_value": self.proposal.new_value,
            "rationale": self.rationale,
        }


@dataclass
class SelfHealResult:
    """The result of running self-heal on one deck.

    Attributes:
        source_file: Where the deck came from (or None for inline text).
        issues_seen: Total lint issues found.
        proposals: Ranked list of ScoredProposal, highest confidence first.
        oracle_passed_before: Whether the original deck passes Flow.
        oracle_passed_after_best: Whether the deck with the highest-
            confidence proposal applied passes Flow.
    """

    source_file: Optional[Path]
    issues_seen: int
    proposals: list[ScoredProposal]
    oracle_passed_before: bool
    oracle_passed_after_best: bool

    def to_dict(self) -> dict:
        return {
            "source_file": str(self.source_file) if self.source_file else None,
            "issues_seen": self.issues_seen,
            "oracle_passed_before": self.oracle_passed_before,
            "oracle_passed_after_best": self.oracle_passed_after_best,
            "proposals": [p.to_dict() for p in self.proposals],
        }


# ---------------------------------------------------------------------------
# Calibration loading
# ---------------------------------------------------------------------------

def load_calibration_report(path: Path) -> Optional[CalibrationReport]:
    """Load a calibration_report.json file. Returns None on failure."""
    if not path.exists():
        return None
    try:
        with open(path) as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return None
    # Reconstruct dataclass instances from the dict.
    per_fixture = []
    for fr in data.get("per_fixture", []):
        attempts = [AttemptResult(**a) for a in fr.get("attempts", [])]
        per_fixture.append(
            FixtureResult(
                path=fr["path"],
                issues_seen=fr["issues_seen"],
                attempts=attempts,
                oracle_passed_before=fr.get("oracle_passed_before", True),
            )
        )
    return CalibrationReport(
        metadata=data.get("metadata", {}),
        summary=data.get("summary", {}),
        per_rule=data.get("per_rule", {}),
        per_fixture=per_fixture,
    )


# ---------------------------------------------------------------------------
# Confidence scoring
# ---------------------------------------------------------------------------

def _score_proposal(
    rule_code: int,
    proposal: FixProposal,
    before_verdict: FlowVerdict,
    after_verdict: FlowVerdict,
    llm_proposed: bool,
    calibration: Optional[CalibrationReport],
) -> ScoredProposal:
    """Compute confidence + rationale for a single proposal.

    The score blends:
    1. Historical calibration rate for the rule (weight 0.4)
    2. Oracle verdict on patched deck (weight 0.4)
    3. Severity weighting (weight 0.1)
    4. LLM penalty (weight 0.1) — proposals from LLMs are downweighted
       vs. mechanical proposals even when verified.
    """
    # 1. Historical calibration rate
    if calibration is not None:
        per_rule = calibration.per_rule.get(str(rule_code), {})
        attempts = per_rule.get("proposals_attempted", 0)
        successful = per_rule.get("proposals_successful", 0)
        if attempts > 0:
            calib_rate = successful / attempts
            # Bayesian-smoothed prior so a single observed success
            # doesn't give 1.0. Smoothing weight 2.0 (Laplace).
            calib_rate = (successful + 1) / (attempts + 2)
        else:
            # No calibration data: default 0.5 (max uncertainty).
            calib_rate = 0.5
    else:
        calib_rate = 0.5  # No calibration report available.

    # 2. Oracle verdict on patched deck
    if before_verdict.passed and after_verdict.passed:
        oracle_score = 1.0
        verified = True
    elif (not before_verdict.passed) and after_verdict.passed:
        oracle_score = 1.0
        verified = True  # The fix made the deck pass.
    elif before_verdict.passed and (not after_verdict.passed):
        oracle_score = 0.0
        verified = False
    else:
        # Both fail: ambiguous. Could be unrelated.
        oracle_score = 0.3
        verified = False

    # 3. Severity weighting — INFO issues get a base discount;
    # WARNING/ERROR get full weight. Since this linter v2 emits
    # most as INFO, we apply a gentle INFO discount rather than a
    # zero-multiplier.
    # Note: severity isn't currently passed in via the LintIssue,
    # so we default to INFO discount.
    severity_score = 0.8  # INFO default

    # 4. LLM penalty
    llm_score = 0.7 if llm_proposed else 1.0

    # Weighted blend
    confidence = (
        0.4 * calib_rate
        + 0.4 * oracle_score
        + 0.1 * severity_score
        + 0.1 * llm_score
    )

    # Rationale
    rationale_parts = [
        f"calib={calib_rate:.2f}",
        f"oracle={'OK' if verified else 'NO'}",
        f"llm={'yes' if llm_proposed else 'no'}",
    ]
    if calibration is None:
        rationale_parts.append("no_calibration_report")

    return ScoredProposal(
        proposal=proposal,
        rule_code=rule_code,
        confidence=confidence,
        verified=verified,
        llm_proposed=llm_proposed,
        oracle_verdict=after_verdict,
        rationale=" ".join(rationale_parts),
    )


# ---------------------------------------------------------------------------
# Oracle application
# ---------------------------------------------------------------------------

def _apply_oracle_to_proposal(
    proposal: FixProposal,
    text: str,
    source_file: Optional[Path],
    cache: dict[str, FlowVerdict],
    oracle_cfg: OracleConfig,
) -> FlowVerdict:
    """Run oracle on the patched deck. Cached by deck text hash."""
    key = proposal.patched_text
    if key in cache:
        return cache[key]
    # Write patched deck to a temp file in the source_file's directory
    # (so INCLUDE paths resolve) and run flow.
    if source_file is not None:
        target_dir = source_file.parent
        deck_path = target_dir / f"{source_file.stem}_proposed.DATA"
    else:
        # No source file: write to a fresh temp dir.
        import tempfile
        target_dir = Path(tempfile.mkdtemp(prefix="self_heal_"))
        deck_path = target_dir / "deck_proposed.DATA"
    deck_path.write_text(proposal.patched_text)
    cfg = OracleConfig(
        flow_binary=oracle_cfg.flow_binary,
        timeout_s=oracle_cfg.timeout_s,
        output_dir=oracle_cfg.output_dir,
        cwd=target_dir,
        dry_run_flag=oracle_cfg.dry_run_flag,
    )
    verdict = run_flow(deck_path, cfg)
    cache[key] = verdict
    return verdict


# ---------------------------------------------------------------------------
# Top-level API
# ---------------------------------------------------------------------------

def self_heal_deck(
    text: str,
    source_file: Optional[Path] = None,
    calibration_report: Optional[CalibrationReport] = None,
    use_llm: bool = False,
    oracle_cfg: Optional[OracleConfig] = None,
    max_proposals: int = 20,
) -> SelfHealResult:
    """Propose and rank fixes for a deck.

    Args:
        text: The deck text.
        source_file: Path to the source file (for INCLUDE resolution
            and source-line reporting). If None, the deck is treated
            as inline.
        calibration_report: CalibrationReport for confidence weighting.
            If None, calibration-based scoring falls back to the prior.
        use_llm: Whether to use an LLM to propose fixes for issues
            without mechanical proposals. (LLM proposals are
            downweighted by the confidence model.)
        oracle_cfg: OracleConfig. Defaults to a 30s timeout.
        max_proposals: Hard cap on returned proposals to bound output
            size. Highest-confidence proposals are returned first.

    Returns:
        SelfHealResult with ranked proposals.
    """
    if oracle_cfg is None:
        oracle_cfg = OracleConfig(timeout_s=DEFAULT_TIMEOUT_S)

    # 1. Lint the deck
    deck = parse_file(text, source_file=source_file)
    resolve_deck(deck)
    result = validate(deck)

    # 2. Oracle on the original
    cache: dict[str, FlowVerdict] = {}
    if source_file is not None:
        before_verdict = run_flow(source_file, oracle_cfg)
    else:
        # No file: construct a synthetic "passed" verdict so downstream
        # scoring works without running the oracle. Real use always
        # passes source_file.
        before_verdict = FlowVerdict(
            deck_path=Path("(inline)"),
            exit_code=0,
            stderr="",
            stdout_tail="",
            error_lines=[],
            fatal_in_stdout=False,
            wallclock_ms=0,
        )

    # 3. For each issue, propose + score
    scored: list[ScoredProposal] = []
    for issue in result.issues:
        proposal = propose_fix(issue, text)
        if proposal is None:
            # No mechanical proposal. LLM fallback (if enabled).
            if not use_llm:
                continue
            llm_proposal = _llm_propose_fix(issue, text, source_file)
            if llm_proposal is None:
                continue
            proposal = llm_proposal
            llm_proposed = True
        else:
            llm_proposed = False

        after_verdict = _apply_oracle_to_proposal(
            proposal, text, source_file, cache, oracle_cfg
        )
        scored.append(
            _score_proposal(
                issue.code, proposal, before_verdict, after_verdict,
                llm_proposed, calibration_report,
            )
        )

    # 4. Rank by confidence (descending), then verified (True first)
    scored.sort(key=lambda sp: (sp.verified, sp.confidence), reverse=True)
    scored = scored[:max_proposals]

    # 5. Oracle verdict on best-proposal-applied deck
    oracle_passed_after_best = before_verdict.passed
    if scored and scored[0].verified:
        oracle_passed_after_best = True

    return SelfHealResult(
        source_file=source_file,
        issues_seen=len(result.issues),
        proposals=scored,
        oracle_passed_before=before_verdict.passed,
        oracle_passed_after_best=oracle_passed_after_best,
    )


# ---------------------------------------------------------------------------
# LLM fallback (gated by feature flag + env var)
# ---------------------------------------------------------------------------

def _llm_propose_fix(
    issue: LintIssue,
    text: str,
    source_file: Optional[Path],
) -> Optional[FixProposal]:
    """Use an LLM to propose a fix for an issue with no mechanical proposal.

    This is gated on the `OPM_AI_USE_LLM_FIXES=1` env var AND the
    presence of the appropriate LLM provider. If either is missing,
    this function returns None and the issue is left unaddressed.

    The LLM is asked to:
    1. Read the issue message and code
    2. Return a JSON patch: {find: <substring>, replace: <substring>, rationale: <str>}

    The patch is applied to the original text and the resulting deck
    is returned in a FixProposal. The oracle downstream will verify
    whether the patch actually fixes the issue.

    Important: this is gated because LLM fixes are slow, expensive,
    and unreliable. They are a last-resort, never a default.
    """
    if os.environ.get("OPM_AI_USE_LLM_FIXES") != "1":
        return None
    try:
        from opm_ai.llm import get_llm_provider  # type: ignore
    except ImportError:
        return None
    provider = get_llm_provider()
    if provider is None:
        return None

    # Build the prompt (kept short; the LLM is given context but not
    # the whole deck to minimize tokens).
    lines = text.splitlines()
    issue_line_idx = max(0, (issue.source_line or 1) - 1)
    context_start = max(0, issue_line_idx - 3)
    context_end = min(len(lines), issue_line_idx + 10)
    context = "\n".join(f"{i+1:4d}  {line}" for i, line in enumerate(
        lines[context_start:context_end], start=context_start
    ))
    prompt = (
        f"You are fixing an OPM Flow .DATA simulation deck.\n"
        f"Issue L{issue.code} (severity={issue.severity.value}): "
        f"{issue.message}\n"
        f"Source line {issue.source_line}.\n\n"
        f"Deck context:\n{context}\n\n"
        f"Reply with JSON only, no markdown:\n"
        f'{{"find": "<exact substring to replace>", '
        f'"replace": "<replacement substring>", '
        f'"rationale": "<one-line explanation>"}}\n'
    )
    try:
        raw = provider.complete(prompt)
    except Exception:
        return None
    try:
        data = json.loads(raw)
        find = data["find"]
        replace = data["replace"]
    except (json.JSONDecodeError, KeyError):
        return None
    if find not in text:
        return None
    patched = text.replace(find, replace, 1)
    return FixProposal(
        rule_code=issue.code,
        issue_keyword=issue.keyword,
        original_text=text,
        patched_text=patched,
        description=f"LLM fix: {data.get('rationale', '?')[:80]}",
        original_value=find[:40],
        new_value=replace[:40],
    )


__all__ = [
    "ScoredProposal",
    "SelfHealResult",
    "load_calibration_report",
    "self_heal_deck",
]